// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.10.1 DO NOT EDIT.
package api

// GetTask defines model for GetTask.
type GetTask struct {
	Description *string `json:"description,omitempty"`
	Title       string  `json:"title"`
	Uuid        string  `json:"uuid"`
}

// PostTask defines model for PostTask.
type PostTask struct {
	Description *string `json:"description,omitempty"`
	Title       string  `json:"title"`
	Uuid        *string `json:"uuid,omitempty"`
}

// PostTaskJSONBody defines parameters for PostTask.
type PostTaskJSONBody PostTask

// ReplaceTaskJSONBody defines parameters for ReplaceTask.
type ReplaceTaskJSONBody PostTask

// PostTaskJSONRequestBody defines body for PostTask for application/json ContentType.
type PostTaskJSONRequestBody PostTaskJSONBody

// ReplaceTaskJSONRequestBody defines body for ReplaceTask for application/json ContentType.
type ReplaceTaskJSONRequestBody ReplaceTaskJSONBody
